resume/urls.py
from django.contrib import admin
# from django.urls import path
from django.conf.urls import url, include
from website.views import home

urlpatterns = [
    url(r'^$', home, name='home'),
    url(r'^admin/', admin.site.urls),
]

website/models.py
from django.db import models


# Create your models here.
class About(models.Model):
    first_name = models.CharField('Name', max_length=250)
    last_name = models.CharField('Name', max_length=250, default='')
    mobile = models.CharField('Mobile', max_length=20)
    email = models.EmailField('Email', max_length=250)
    address = models.CharField('Address', max_length=250)
    designation = models.CharField('Designation', max_length=250)
    description = models.TextField('Description')

    def __str__(self):
        return self.first_name


class Social(models.Model):
    facebook = models.CharField('Facebook', max_length=100)
    twitter = models.CharField('Twitter', max_length=100)
    linkedin = models.CharField('LinkedIn', max_length=100)
    google_plus = models.CharField('GooglePlus', max_length=100)
    github = models.CharField('Github', max_length=100)
    youtube = models.CharField('Youtube', max_length=100)

    def __str__(self):
        return "Social Media"


class Experience(models.Model):
    designation = models.CharField('Designation', max_length=250)
    company = models.CharField('Company', max_length=250)
    start_date = models.DateField('Start Date')
    end_date = models.DateField('End Date')
    description = models.TextField('Description')

    def __str__(self):
        return self.company + ' ' + self.designation


class Education(models.Model):
    school = models.CharField('School', max_length=250)
    degree = models.CharField('Degree', max_length=250)
    obtain_gpa = models.FloatField("Obtain GPA")
    total_gpa = models.FloatField("Total GPA")
    start_date = models.DateField('Start Date')
    end_date = models.DateField('End Date')

    def __str__(self):
        return self.school


class SkillCategory(models.Model):
    title = models.CharField('Title', max_length=250)
    order = models.IntegerField('Order', default=0)

    def __str__(self):
        return self.title


class Skill(models.Model):
    COLOR = {
        ('bg-primary', 'Primary'),
        ('bg-success', 'Success'),
        ('bg-info', 'Info'),
        ('bg-warning', 'Warning'),
        ('bg-danger', 'Danger'),
    }
    title = models.CharField('Title', max_length=250)
    category = models.ForeignKey(SkillCategory, on_delete=models.CASCADE)
    level = models.IntegerField('Level')
    color = models.CharField('Color', max_length=50, choices=COLOR, default='bg-success')
    order = models.IntegerField('Order', default=0)

    class Meta:
        ordering = ['order']

    def __str__(self):
        return self.title

website/views.py
from django.shortcuts import render
from .models import *


# Create your views here.
def home(request):
    data = {}
    data['about'] = About.objects.all()[0]
    data['social'] = Social.objects.all()[0]
    data['experiences'] = Experience.objects.order_by("-id").all()
    data['educations'] = Education.objects.order_by("-id").all()
    data['skillCategories'] = SkillCategory.objects.order_by("order").all()
    return render(request, 'index.html', data)

website/templates/index.html
<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{{ about.first_name }} {{ about.last_name }}</title>

    <!-- Bootstrap core CSS -->
    <link href="{{ STATIC_URL }}vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom fonts for this template -->
    <link href="https://fonts.googleapis.com/css?family=Saira+Extra+Condensed:100,200,300,400,500,600,700,800,900" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i,800,800i" rel="stylesheet">
    <link href="{{ STATIC_URL }}vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet">
    <link href="{{ STATIC_URL }}vendor/devicons/css/devicons.min.css" rel="stylesheet">
    <link href="{{ STATIC_URL }}vendor/simple-line-icons/css/simple-line-icons.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{{ STATIC_URL }}css/resume.min.css" rel="stylesheet">
    <link href="{{ STATIC_URL }}css/style.css" rel="stylesheet">

  </head>

  <body id="page-top">

    <nav class="navbar navbar-expand-lg navbar-dark bg-primary fixed-top" id="sideNav">
      <a class="navbar-brand js-scroll-trigger" href="#page-top">
        <span class="d-block d-lg-none">Start Bootstrap</span>
        <span class="d-none d-lg-block">
          <img class="img-fluid img-profile rounded-circle mx-auto mb-2" src="{{ STATIC_URL }}img/profile.jpg" alt="">
        </span>
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link js-scroll-trigger" href="#about">About</a>
          </li>
          <li class="nav-item">
            <a class="nav-link js-scroll-trigger" href="#experience">Experience</a>
          </li>
          <li class="nav-item">
            <a class="nav-link js-scroll-trigger" href="#education">Education</a>
          </li>
          <li class="nav-item">
            <a class="nav-link js-scroll-trigger" href="#skills">Skills</a>
          </li>
{#          <li class="nav-item">#}
{#            <a class="nav-link js-scroll-trigger" href="#interests">Interests</a>#}
{#          </li>#}
{#          <li class="nav-item">#}
{#            <a class="nav-link js-scroll-trigger" href="#awards">Awards</a>#}
{#          </li>#}
        </ul>
      </div>
    </nav>

    <div class="container-fluid p-0">

      <section class="resume-section p-3 p-lg-5 d-flex d-column" id="about">
        <div class="my-auto">
          <h1 class="mb-0">{{ about.first_name }}
            <span class="text-primary">{{ about.last_name }}</span>
          </h1>
          <div class="subheading mb-5 address">{{ about.address }} · {{ about.mobile }} ·
            <a class="email" href="mailto:name@email.com">{{ about.email }}</a>
          </div>
          <p class="mb-5"> {{ about.description | safe }} </p>
          <ul class="list-inline list-social-icons mb-0">

              {% if social.facebook %}
                <li class="list-inline-item">
                  <a href="{{ social.facebook }}" target="_blank">
                    <span class="fa-stack fa-lg">
                      <i class="fa fa-circle fa-stack-2x"></i>
                      <i class="fa fa-facebook fa-stack-1x fa-inverse"></i>
                    </span>
                  </a>
                </li>
              {% endif %}

          {% if social.twitter %}
            <li class="list-inline-item">
              <a href="{{ social.twitter }}" target="_blank">
                <span class="fa-stack fa-lg">
                  <i class="fa fa-circle fa-stack-2x"></i>
                  <i class="fa fa-twitter fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            </li>
          {% endif %}


          {% if social.linkedin %}
            <li class="list-inline-item">
              <a href="{{ social.linkedin }}" target="_blank">
                <span class="fa-stack fa-lg">
                  <i class="fa fa-circle fa-stack-2x"></i>
                  <i class="fa fa-linkedin fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            </li>
          {% endif %}

          {% if social.github %}
            <li class="list-inline-item">
              <a href="{{ social.github }}" target="_blank">
                <span class="fa-stack fa-lg">
                  <i class="fa fa-circle fa-stack-2x"></i>
                  <i class="fa fa-github fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            </li>
          {% endif %}

          {% if social.youtube %}
            <li class="list-inline-item">
              <a href="{{ social.youtube }}" target="_blank">
                <span class="fa-stack fa-lg">
                  <i class="fa fa-circle fa-stack-2x"></i>
                  <i class="fa fa-youtube fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            </li>
          {% endif %}

          {% if social.google_plus %}
            <li class="list-inline-item">
              <a href="{{ social.google_plus }}" target="_blank">
                <span class="fa-stack fa-lg">
                  <i class="fa fa-circle fa-stack-2x"></i>
                  <i class="fa fa-google-plus fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            </li>
          {% endif %}

          </ul>
        </div>
      </section>

      <section class="resume-section p-3 p-lg-5 d-flex flex-column" id="experience">
        <div class="my-auto">
          <h2 class="mb-5">Experience</h2>

          {% for experience in experiences %}
              <div class="resume-item d-flex flex-column flex-md-row mb-5">
                <div class="resume-content mr-auto">
                  <h3 class="mb-0">{{ experience.designation }}</h3>
                  <div class="subheading mb-3">{{ experience.company }}</div>
                  <p>{{ experience.description }}</p>
                </div>
                <div class="resume-date text-md-right">
                  <span class="text-primary">{{ experience.start_date }} - {{ experience.end_date }}</span>
                </div>
              </div>
          {% endfor %}



        </div>

      </section>

      <section class="resume-section p-3 p-lg-5 d-flex flex-column" id="education">
        <div class="my-auto">
          <h2 class="mb-5">Education</h2>

          {% for education in educations %}
              <div class="resume-item d-flex flex-column flex-md-row mb-5">
                <div class="resume-content mr-auto">
                  <h3 class="mb-0">{{ education.school }}</h3>
                  <div class="subheading mb-3">{{ education.degree }}</div>
{#                  <div>Computer Science - Web Development Track</div>#}
                  <p>GPA: {{ education.obtain_gpa }} ( Out of {{ education.total_gpa }} )</p>
                </div>
                <div class="resume-date text-md-right">
                  <span class="text-primary">{{ experience.start_date }} - {{ experience.end_date }}</span>
                </div>
              </div>
          {% endfor %}
        </div>
      </section>








    <section class="resume-section p-3 p-lg-5 d-flex flex-column" id="skills">
        <div class="my-auto">
          <h2 class="mb-5">Skills</h2>
              {% for skillCategory in skillCategories %}
                  <div class="single-skill">
                  <i class="fa-li fa fa-check"></i>
                    <strong class="text-uppercase skill-category-title"> {{ skillCategory.title }} </strong>
                    <div class="row clearfix">
                        {% for skill in skillCategory.skill_set.all %}
                        <div class="col-md-6 skill-item">
                            <div class="row clearfix">
                                <div class="col-md-4 text-right skill-title"> {{ skill.title }} : </div>
                                <div class="col-md-8">
                                    <div class="progress">
                                      <div class="progress-bar progress-bar-striped {{ skill.color }}" role="progressbar" style="width: {{ skill.level }}%" aria-valuenow="{{ skill.level }}" aria-valuemin="0" aria-valuemax="100">
{#                                          {{ skill.level }}%#}
                                      </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                  </div>
              {% endfor %}
        </div>
      </section>









{#      <section class="resume-section p-3 p-lg-5 d-flex flex-column" id="skills">#}
{#        <div class="my-auto">#}
{#          <h2 class="mb-5">Skills</h2>#}
{#          <ul class="fa-ul mb-0">#}
{#              {% for skillCategory in skillCategories %}#}
{#                <li>#}
{#                  <i class="fa-li fa fa-check"></i>#}
{#                    <strong class="text-uppercase"> {{ skillCategory.title }} </strong>#}
{#                    <table class="table">#}
{#                        {% for skill in skillCategory.skill_set.all %}#}
{#                            <tr>#}
{#                                <th class="text-right" style="width: 190px">{{ skill.title }} </th>#}
{#                                <td>#}
{#                                    <div class="progress">#}
{#                                      <div class="progress-bar progress-bar-striped {{ skill.color }}" role="progressbar" style="width: {{ skill.level }}%" aria-valuenow="{{ skill.level }}" aria-valuemin="0" aria-valuemax="100">#}
{#                                          {{ skill.level }}%#}
{#                                      </div>#}
{#                                    </div>#}
{#                                </td>#}
{#                            </tr>#}
{#                        {% endfor %}#}
{#                    </table>#}
{#                </li>#}
{#              {% endfor %}#}
{#          </ul>#}
{#        </div>#}
{#      </section>#}






{##}
{#      <section class="resume-section p-3 p-lg-5 d-flex flex-column" id="interests">#}
{#        <div class="my-auto">#}
{#          <h2 class="mb-5">Interests</h2>#}
{#          <p>Apart from being a web developer, I enjoy most of my time being outdoors. In the winter, I am an avid skiier and novice ice climber. During the warmer months here in Colorado, I enjoy mountain biking, free climbing, and kayaking.</p>#}
{#          <p class="mb-0">When forced indoors, I follow a number of sci-fi and fantasy genre movies and television shows, I am an aspiring chef, and I spend a large amount of my free time exploring the latest technolgy advancements in the front-end web development world.</p>#}
{#        </div>#}
{#      </section>#}
{##}
{#      <section class="resume-section p-3 p-lg-5 d-flex flex-column" id="awards">#}
{#        <div class="my-auto">#}
{#          <h2 class="mb-5">Awards &amp; Certifications</h2>#}
{#          <ul class="fa-ul mb-0">#}
{#            <li>#}
{#              <i class="fa-li fa fa-trophy text-warning"></i>#}
{#              Google Analytics Certified Developer</li>#}
{#            <li>#}
{#              <i class="fa-li fa fa-trophy text-warning"></i>#}
{#              Mobile Web Specialist - Google Certification</li>#}
{#            <li>#}
{#              <i class="fa-li fa fa-trophy text-warning"></i>#}
{#              1<sup>st</sup>#}
{#              Place - University of Colorado Boulder - Emerging Tech Competition 2009</li>#}
{#            <li>#}
{#              <i class="fa-li fa fa-trophy text-warning"></i>#}
{#              1<sup>st</sup>#}
{#              Place - University of Colorado Boulder - Adobe Creative Jam 2008 (UI Design Category)</li>#}
{#            <li>#}
{#              <i class="fa-li fa fa-trophy text-warning"></i>#}
{#              2<sup>nd</sup>#}
{#              Place - University of Colorado Boulder - Emerging Tech Competition 2008</li>#}
{#            <li>#}
{#            <li>#}
{#              <i class="fa-li fa fa-trophy text-warning"></i>#}
{#              1<sup>st</sup>#}
{#              Place - James Buchanan High School - Hackathon 2006</li>#}
{#            <li>#}
{#              <i class="fa-li fa fa-trophy text-warning"></i>#}
{#              3<sup>rd</sup>#}
{#              Place - James Buchanan High School - Hackathon 2005</li>#}
{#          </ul>#}
{#        </div>#}
{#      </section>#}




    </div>

    <!-- Bootstrap core JavaScript -->
    <script src="{{ STATIC_URL }}vendor/jquery/jquery.min.js"></script>
    <script src="{{ STATIC_URL }}vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Plugin JavaScript -->
    <script src="{{ STATIC_URL }}vendor/jquery-easing/jquery.easing.min.js"></script>

    <!-- Custom scripts for this template -->
    <script src="{{ STATIC_URL }}js/resume.min.js"></script>

  </body>

</html>